name: narayana-frontend
static_sites:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    error_document: index.html
    routes:
      - path: /
    catchall_document: index.html
